# Databricks app configuration file

command: ["uvicorn", "--app-dir", "./src", "terrametria.backend:app"]

env:
  - name: "TERRAMETRIA_CATALOG"
    value: "ivt"
  - name: "TERRAMETRIA_SCHEMA"
    value: "terrametria"